
import { Inter } from 'next/font/google'

import Head from 'next/head';
import '@/app/globals.css'
import '/public/common.css'
import '/public/fontawesome/css/all.css'
/* import 'https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css'
import 'https://fonts.googleapis.com/earlyaccess/notosanskr.css' */
import Nav from '@/app/components/Nav.jsx';
import Header from '@/app/components/Header.jsx';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '슈파마켓',
  description: 'Generated by create next app',
  keywords: ['슈파마켓', 'Next.js', 'React', '웹 개발'],
  canonical: 'https://example.com/canonical-url',
  robots: 'index, follow',
  author: 'Your Name',
  url: 'https://example.com/page-url',
  image: 'https://supabase.com/dashboard/favicon/favicon.ico',
  favicon: 'https://supabase.com/dashboard/favicon/favicon.ico',

}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      
      <body className={inter.className}>

        <div className="wrap">
          <Header />
          <div className="container page">
            {children}
          </div>
          <Nav />
        </div>
      </body>
    </html>
  )
}
