
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Head from 'next/head';
import './globals.css'
import '/public/common.css'
/* import 'https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css'
import 'https://fonts.googleapis.com/earlyaccess/notosanskr.css' */
import Nav from './components/Nav.jsx';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '슈파마켓',
  description: 'Generated by create next app',
  keywords: ['슈파마켓', 'Next.js', 'React', '웹 개발'],
  canonical: 'https://example.com/canonical-url',
  robots: 'index, follow',
  author: 'Your Name',
  url: 'https://example.com/page-url',
  image: 'https://supabase.com/dashboard/favicon/favicon.ico',
  favicon: 'https://supabase.com/dashboard/favicon/favicon.ico',

}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      
      <body className={inter.className}>

        <div className="wrap">
          <header className={`header`}>
            <div className="inr">
              <div className="ldt">
                <a href="/" className="logo">
                  <span className="btlogo"></span>
                  <span className="txt">SUPAMARKET</span>
                  <Image className="next" src="/next.svg" alt="Next.js Logo" width={26} height={27} priority />
                </a>
          
              </div>
              <div className="rdt">
          
          
                <button type="button" className="bt gnb"><i className="fa-regular fa-bars"></i><b>메뉴</b></button>
              </div>
            </div>
          </header>
          <div className="container page">
            {children}
          </div>
          <Nav />
        </div>
      </body>
    </html>
  )
}
